#!/usr/bin/env bash
# Modified from https://github.com/winapps-org/winapps/blob/main/bin/winapps

set -o errexit
set -o pipefail
set -o nounset

readonly EC_FAIL_START=3
readonly EC_FAIL_RESUME=4
readonly EC_FAIL_DESTROY=5
readonly EC_SD_TIMEOUT=6
readonly EC_DIE_TIMEOUT=7
readonly EC_NOT_EXIST=8
readonly EC_NOT_IN_GROUP=9

readonly VM_NAME='win11'

FREERDP_PID=-1

trap cleanup EXIT

cleanup() {
  # Kill FreeRDP
  (( FREERDP_PID > 0 )) && kill -9 "${FREERDP_PID}" &>/dev/null

  # Terminate the script
  exit
}

send_notification() {
  # Declare variables
  local message="$1"
  local -i duration="${2:-3}"

  # Read from stdin if `message` is unset
  if [[ -z "${message}" ]]; then
    while IFS= read -r line; do
      message+="${line}"
    done
  fi

  # Convert to milliseconds
  (( duration *= 1000 ))
  
  notify-send --expire-time="${duration}" --urgency='low' 'Windows' "${message}"
}

exit_with_error() {
  # Declare error code variable
  local -i err_code="$1"
  
  # Notify user of specific error
  case "${err_code}" in
    "${EC_FAIL_START}")
      send_notification 'The virtual machine failed to start.' '8'
      err_code=69
      ;;
    "${EC_FAIL_RESUME}")
      send_notification 'The virtual machine failed to resume.' '8'
      err_code=69
      ;;
    "${EC_FAIL_DESTROY}")
      send_notification \
        'The virtual machine failed to shut down forcefully.' \
        '8'
      err_code=69
      ;;
    "${EC_SD_TIMEOUT}")
      send_notification 'The virtual machine took too long to shut down.' '8'
      err_code=69
      ;;
    "${EC_DIE_TIMEOUT}")
      send_notification 'The virtual machine took too long to die.' '8'
      err_code=69
      ;;
    "${EC_NOT_EXIST}")
      send_notification 'The virtual machine does not exist.' '8'
      err_code=69
      ;;
    "${EC_NOT_IN_GROUP}")
      send_notification \
        "The user $(id -nu) is not part of the required groups." \
        '8'
      err_code=77
      ;;
  esac

  # Terminate the script
  exit "${err_code}"
}

is_vm_running() {
  # Declare exit status variable
  local -i exit_status=0

  # Declare timer variables
  local -i time_elapsed=0
  local -i time_limit=60
  local -i time_interval=5

  # Attempt to start Windows VM
  if (virsh list --all --name | xargs | grep -wq "${VM_NAME}"); then
    if (virsh list --state-shutoff --name | xargs | grep -wq "${VM_NAME}"); then
      send_notification 'Booting the virtual machine.'
      virsh start "${VM_NAME}" &>/dev/null || exit_status="${EC_FAIL_START}"
      if (virsh list --state-paused --name \
        | xargs \
        | grep -wq "${VM_NAME}"); then
        send_notification 'Resuming the virtual machine.'
        virsh resume "${VM_NAME}" &>/dev/null || exit_status="${EC_FAIL_RESUME}"
      fi
    elif (virsh list --state-paused --name \
      | xargs \
      | grep -wq "${VM_NAME}"); then
      send_notification 'Resuming the virtual machine.'
      virsh resume "${VM_NAME}" &>/dev/null || exit_status="${EC_FAIL_RESUME}"
    elif (virsh list --state-other --name | xargs | grep -wq "${VM_NAME}"); then
      if (virsh domstate "${VM_NAME}" | xargs | grep -wq 'shutdown'); then
        send_notification '' '' <<-END
					The virtual machine is currently shutting down.\n
					It will automatically restart once the shutdown process is complete.
				END
        exit_status="${EC_SD_TIMEOUT}"
        while (( time_elapsed < time_limit )); do
          if (virsh list --state-shutoff --name \
            | xargs \
            | grep -wq "${VM_NAME}"); then
            exit_status=0
            send_notification 'Booting the virtual machine.'
            virsh start "${VM_NAME}" &>/dev/null ||
              exit_status="${EC_FAIL_START}"
            break
          fi
          sleep "${time_interval}"
          (( time_elapsed += time_interval ))
        done
      elif (virsh domstate "${VM_NAME}" | xargs | grep -wq 'crashed'); then
        send_notification '' '' <<-END
					The virtual machine experienced an unexpected crash.\n
					Attempting to restart.
				END
        virsh destroy "${VM_NAME}" &>/dev/null ||
          exit_status="${EC_FAIL_DESTROY}"
        if (( exit_status == 0 )); then
          send_notification 'Booting the virtual machine.'
          virsh start "${VM_NAME}" &>/dev/null || exit_status="${EC_FAIL_START}"
        fi
      elif (virsh domstate "${VM_NAME}" | xargs | grep -wq 'dying'); then
        send_notification '' '' <<-END
					The virtual machine is currently shutting down unexpectedly.\n
					It will try to restart once the shutdown process finishes.
				END
        exit_status="${EC_DIE_TIMEOUT}"
        while (( time_elapsed < time_limit )); do
          if (virsh domstate "${VM_NAME}" | xargs | grep -wq 'crashed'); then
            exit_status=0
            send_notification '' '' <<-END
							The virtual machine experienced an unexpected crash.\n
							Attempting to restart.
						END
            virsh destroy "${VM_NAME}" &>/dev/null ||
              exit_status="${EC_FAIL_DESTROY}"
            if (( exit_status == 0 )); then
              send_notification 'Booting the virtual machine.'
              virsh start "${VM_NAME}" &>/dev/null ||
                exit_status="${EC_FAIL_START}"
            fi
            break
          elif (virsh list --state-shutoff --name \
            | xargs \
            | grep -wq "${VM_NAME}"); then
            exit_status=0
            send_notification 'Booting the virtual machine.'
            virsh start "${VM_NAME}" &>/dev/null ||
              exit_status="${EC_FAIL_START}"
            break
          fi
          sleep "${time_interval}"
          (( time_elapsed += time_interval ))
        done
      elif (virsh domstate "${VM_NAME}" | xargs | grep -wq 'pmsuspended'); then
        virsh resume "${VM_NAME}" &>/dev/null || exit_status="${EC_FAIL_RESUME}"
      fi
    fi
  else
    exit_status="${EC_NOT_EXIST}"
  fi

  # Handle non-zero exit status
  (( exit_status != 0)) && exit_with_error "${exit_status}"
}

is_user_group_member() {
  # Identify groups the current user belongs to
  local user_groups="$(groups "$(whoami)")"

  if ! (grep -qE '\bkvm\b' <<< "${user_groups}") ||
    ! (grep -qE '\blibvirt\b' <<< "${user_groups}"); then
    exit_with_error "${EC_NOT_IN_GROUP}"
  fi
}

main() {
  is_user_group_member
  is_vm_running
}

main "$@"
